input:
  genome_fasta: "data/input/phiX_genome.fasta"

output:
  directories:
    faste_files: "data/output/faste_files"
    results: "data/output/results"

sequencing:
  read_length:
    - 50
    - 100
    - 150
  num_reads:
    - 500
    - 1000
    - 2000

assembly:
  min_overlap: 20
  error_prob:
    - 0
    - 0.01
    - 0.05
