input:
  genome_fasta: "data/input/phiX_genome.fasta"

output:
  directories:
    faste_files: "data/output/faste_files"
    results: "data/output/results"

sequencing:
  read_length:
    - 30
    - 60
    - 90
    - 120
    - 150

  num_reads:
    - 300
    - 600
    - 900
    - 1200
    - 1500

assembly:
  min_overlap: 20
  error_probabilities:
    - 0
    - 0.01
    - 0.03
    - 0.05
    - 0.07
